### ISSUE TITLE
Leveling without having enough exp

### ISSUE THREAD

**Issue by Foxiallis** [Senior-S/JustLeveling-Fork#11]
Steps to reproduce
1. Have more than enough levels to level up a skill (e.g. if you need 5 levels to level up a skill you should have at least 6 levels)
2. Rapidly mash the level up button
3. The skill will level up 2, sometimes 3 and even 4 times
4. This causes you to have negative experience (so when you die your score shows as, for example, -2000) but you gain levels normally so you basically gained a few levels for free

This was tested on a multiplayer server during a laggy period. As I surmise, the button checks if you have enough experience, and if so sends a signal to level up - but this signal doesn't have a check of his own. So in a low TPS situation if you send a few signals before the button blacks out, all these signals will be received on server and processed without checks, causing you to level up way faster than you should have. My advise is to double-check the signal, meaning additionally check if the player has enough exp not only when sending the signal, but when receiving it too.

**Comment by Foxiallis** [comment]
Oh yeah I forgot to mention - minecraft doesn't handle negative xp, so if you have negative score it would just treat it as zero and you would earn experience like you usually do

**Comment by Senior-S** [comment]
Fixed on 1.1.5
https://github.com/Senior-S/JustLeveling-Fork/releases/tag/1.1.5

**Comment by Foxiallis** [comment]
This issue still appears on 1.1.5, exactly the same way of implementing
